### ISSUE TITLE
diagrama de clases actividad 7

### ISSUE THREAD

**Issue by ang3-l32** [SistemasTecTlaxiaco/practica-7-diagrama-de-clases-unidad-5#1]
[PRACTICA_1_TEMA_3_INGENIERIA_DE_SOFTWARE.pdf](https://github.com/SistemasTecTlaxiaco/practica-7-diagrama-de-clases-unidad-5/files/11594219/PRACTICA_1_TEMA_3_INGENIERIA_DE_SOFTWARE.pdf)

**Comment by josealfredo79** [comment]
Calificacion???

**Comment by NoeliaGlez** [comment]
calificación= 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
